# ----------------------------------------------------------------------------
# caktus.django-k8s
# ----------------------------------------------------------------------------

env_database_url: "postgres://{{ app_name }}_staging:{{ database_password }}@{{ DatabaseAddress }}:5432/{{ app_name }}_{{ env_name }}"
# pwgen -s 40 1|tr -d '\n'|ansible-vault encrypt_string
database_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31633236353234623634616635306235633431373936393632656266333831333335326565353536
  6565353434336561386234346639626634363164613139620a333134643231643634373137323638
  62366363386436613935323163663562313865326236306662333765613565353037386332323134
  3631346233636465350a646135386165336631383837383436653638346361333862663035613066
  61383363666334303639353661353862363433383833643164623865636363383162343666636132
  3135306661623561633630323062613065623738383866653833

# Disaster Recovery: DB restore configuration
k8s_restore_namespace: "{{ k8s_namespace }}"
k8s_restore_target_db_url: "{{ env_database_url }}"
k8s_restore_sql_commands: [CREATE EXTENSION IF NOT EXISTS citext;]
k8s_restore_maint_user: hip_admin
k8s_restore_maint_host: "{{ DatabaseAddress }}"
k8s_restore_maint_port: "5432"
k8s_restore_maint_name: hip
k8s_restore_maint_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63666133363834643339373132356631656633343463313761376363613138383035353532346236
  3162396136333434303539346435306361336636636232620a353139306565616231303763646366
  31636366666262323933643061626135346663646564656534313437393063396633626332663831
  3565323636626163320a633963393664626563313265363632633161643833626366373265643835
  30383637393636336335303231653434666536623535313439646136663239383139323533613239
  6666643563326336613864366161623264363331656632333761


# Azure SSO settings
azure_client_id: "f0629cf8-f6f4-4142-94c3-11b8beaaa510"
azure_tenant_id: "2046864f-68ea-497d-af34-a6629a6cd700"
azure_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63393564633738356436383239383834376138383961376361623564643939376139663032363136
  3736303133396464623065653735376634353332616562650a316664383865383264326161353765
  63623533373162346439663263363263343364396538323139343830653830616261656262623064
  3137343165353866610a353836383835623065666438363033353930396132333233633164303565
  35623661353662303333393232623961306539386533343835613333373264353938636265336233
  3834613936393733316136653464313630363861303763643832